# Custom Language File for Launcher Customizer

[ejs.app]
title = "Bedragoth Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Maxime-DevPro/Bedragoth"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/eazDhQwc9f"

[ejs.settings]
sourceGithubLink = "https://github.com/Maxime-DevPro/Bedragoth"
supportLink = "https://github.com/Maxime-DevPro/Bedragoth/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue en Bedragoth"
welcomeDescription = "Préparez-vous pour votre nouvelle aventure."
welcomeDescCTA = "Tu es à quelques clics seulement de Bedragoth."
