[ejs.landing]
updateAvailableTooltip = "Update Available"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOUVELLES"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "S'il vous plaît, attendez.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Rechercher des nouvelles.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Essayer à nouveau"
newsErrorNoneSpan = "Pas de nouvelles"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION À MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "E-MAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié?"
loginRememberMeText = "Se souvenir de moi?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connectez-vous avec Microsoft"
loginWithMojang = "Connectez-vous avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionnez un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Fait"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gérez ceux existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancez-vous en plein écran."
autoConnectTitle = "Connectez-vous automatiquement au serveur au lancement."
launchDetachedTitle = "Lancez le processus de jeu détaché du lanceur."
launchDetachedDesc = "Si le jeu n'est pas détaché, la fermeture du lanceur fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver mods."
switchServerButton = "Changer"
requiredMods = "Requis Mods"
optionalMods = "Facultatif Mods"
dropinMods = "Drop-in Mods"
addMods = "Ajouter des Mods"
dropinRefreshNote = "(F5 pour rafraîchir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activez ou désactivez les shaders. Veuillez noter que les shaders ne fonctionneront correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner Shaderpack"
tabJavaHeaderText = "Java Paramètres"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "Maximum RAM"
minRAM = "Minimum RAM"
memoryDesc = "La RAM minimale recommandée est de 3 Go. Définir les valeurs minimale et maximale sur la même valeur peut réduire le décalage."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Java Exécutable"
javaExecSelDialogTitle = "Sélectionner Java Exécutable"
javaExecSelButtonText = "Choisir le fichier"
javaExecDesc = "Le Java Exécutable est validé avant le lancement du jeu."
javaPathDesc = "Le chemin devrait se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Supplémentaire JVM Options"
jvmOptsDesc = "Options à fournir à la JVM au moment de l'exécution. <em>-Xms</em> and <em>-Xmx</em> ne devrait pas être inclus."
launcherTabHeaderText = "Launcher Paramètres"
launcherTabHeaderDesc = "Options liées au lanceur lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour préliminaires."
allowPrereleaseDesc = "Les pré-versions incluent de nouvelles fonctionnalités qui n'ont peut-être pas été entièrement testées ou intégrées.<br>Cela sera toujours vrai si vous utilisez une version préliminaire."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner Data Directory"
chooseFolder = "Choisir le dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locales seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes sont stockées dans le dossier d'instance pour la configuration de serveur correspondante."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Afficher les informations et les notes de version pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Pas de Release Notes"
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "Mises à jour du lanceur"
launcherUpdatesHeaderDesc = "Téléchargez, installez et consultez les mises à jour du lanceur."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Mettre à jour les notes de version"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUE"


[js.discord]
waiting = "En attente du client.."
state = "{shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "SE CONNECTER"
loggingIn = "SE CONNECTER"
success = "SUCCÈS"
tryAgain = "Essayer à nouveau"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "S'il vous plaît, attendez.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir console (CTRL + Shift + i) pour plus de détails."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations sur le système.."
noCompatibleJava = "Non compatible<br>Installation Java trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation Java 64 bits {major}. Souhaitez-vous que nous installions une copie?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement Java"
javaDownloadFailureText = "Voir console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = '.<br><br><a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java"></a>'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un problème, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations sur le serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "S'il vous plaît, attendez.."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la vérification du fichier"
downloadingFiles = "Téléchargement de fichiers.."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement du fichier"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé correctement. Résultat, le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>"
doneEnjoyServer = "Bon voyage en Bedragoth!"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Recherche des nouvelles"

[js.landing.discord]
loading = "Serveur Roleplay!"
joining = "Serveur Roleplay!"
joined = "."

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "La déconnexion de Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionnez un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avertissement<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le lanceur, vous devez être connecté à au moins un compte. Vous devrez ensuite vous reconnecter.<br><br>Êtes-vous sûr de vouloir vous déconnecter?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionnez un compte"
selectedAccount = "Sélectionnez un compte ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de la suppression<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec du basculement<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Selection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Echec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l'index de distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour le chargement. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur le serveur. Le lanceur ne peut pas démarrer sans cela. Assurez-vous d'être connecté à Internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous connecter à nouveau."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Se connecter"
selectAnotherAccountButton = "Sélectionnez un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur lors de la connexion : Profil non configuré"
noProfileDesc = "Votre compte Microsoft n’a pas encore de profil Minecraft configuré. Si vous avez récemment acheté le jeu ou l’avez récupéré via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n’avez pas encore acheté le jeu, vous pouvez également le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur lors de la connexion: Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n’a aucun compte Xbox associé."
xblBannedTitle = "Erreur lors de la connexion : Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d’un pays où Xbox Live n’est pas disponible ou est interdit."
under18Title = "Erreur lors de la connexion : Approbation parentale requise"
under18Desc = "Les comptes pour les utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s’est produite. Veuillez consulter la console (Ctrl+Shift+i) pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne: Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne<br>Non trouvé"
notFoundDesc = "Le point d’authentification n’a pas été trouvé. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur lors de la connexion:<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Essayez à nouveau en utilisant l’e-mail du compte comme nom d’utilisateur."
invalidCredentialsTitle = "Erreur lors de la connexion:<br>Identifiants invalides"
invalidCredentialsDesc = "E-mail ou le mot de passe que vous avez saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur lors de la connexion<br>Token Invalide"
invalidTokenDesc = "Le Token d'accès fourni est invalide."
tokenHasProfileTitle = "Erreur lors de la connexion:<br>Le Token possède déjà un profil"
tokenHasProfileDesc = "Le Token a déjà un profil attribué. La sélection de profils n’est pas encore implémentée."
credentialsMissingTitle = "Erreur lors de la connexion: Identifiants manquants"
credentialsMissingDesc = "Le nom d’utilisateur/mot de passe n’a pas été soumis ou le mot de passe comporte moins de 3 caractères."
invalidSaltVersionTitle = "Erreur lors de la connexion : Version Salt invalide"
invalidSaltVersionDesc = "Version de Salt invalide."
unsupportedMediaTypeTitle = "Erreur interne: Type de média non pris en charge"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur lors de la connexion:<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur lors de la connexion:<br>Serveur inaccessible"
unreachableDesc = "Impossible de joindre les serveurs d’authentification. Assurez-vous qu’ils sont en ligne et que vous êtes connecté à Internet."
gameNotPurchasedTitle = "Erreur lors de la connexion:<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte que vous essayez d’utiliser n’a pas acheté de copie de Minecraft. Vous pouvez acheter une copie sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s’est produite. Veuillez consulter la console (Ctrl+Shift+i) pour plus de détails."
